spring.config:
    activate:
      on-profile: prod
server.port: 2022
spring.mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

spring.datasource.url: jdbc:mysql://127.0.0.1:3306/Project1
spring.datasource.username: root
spring.datasource.password: Rootpass12
spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring:
  jpa:
    database-platform=org:
      hibernate:
        dialect:
          MySQL8InnoDBDialect
spring.jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
jackson.serialization:
      fail-on-empty-beans: false
spring.mail:
    host: smtp.gmail.com
    port: 587
    username: bcm.forprogress@gmail.com
    password: tcpliaoolvqtcwhm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
