spring.environment: default
server.port: 2022
spring.mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

spring.datasource.url: jdbc:mysql://127.0.0.1:3306/project1
spring.datasource.username: root
spring.datasource.password: Rome2totalwar
spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring:
  jpa:
    database-platform=org:
      hibernate:
        dialect:
          MySQL8InnoDBDialect
spring.jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
jackson.serialization:
      fail-on-empty-beans: false
---
spring:
  config:
    activate:
      on-profile: prod
server.port: 2024
---
spring:
  config:
    activate:
      on-profile: test
server.port: 2023